apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-deployment.yaml
  # - backend-deployment.yaml
namespace: default
images:
  - name: frontend
    newName: leui/tcc-frontend-prod
    newTag: latest
  # - name: backend
  #   newName: leui/tcc-backend
  #   newTag: latest
